# Generated by Django 6.0.8 on 2026-08-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='scrapbook/')),
                ('rotation', models.IntegerField(default=0, help_text='Rotation in degrees. Example: -3, 0, 4')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrapbook_items', to='core.category')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
