# Generated by Django 6.0.8 on 2026-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_badge', models.CharField(default='THE ARCHIVE STORY', max_length=100)),
                ('story_title', models.CharField(default='Three Years. Countless Memories. One Story.', max_length=200)),
                ('story_paragraph_1', models.TextField(default='College Memories ’26 is a digital archive created to preserve the people, journeys, celebrations and everyday moments that defined our three years of college life.')),
                ('story_paragraph_2', models.TextField(default='It is more than a gallery of photographs. It is a collection of friendships, laughter, lessons and memories that will continue to stay with us long after graduation.')),
                ('story_paragraph_3', models.TextField(default='Built as a lightweight and permanent digital archive, this platform allows every member of our batch to revisit our journey anytime and anywhere.')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('story_image_alt', models.CharField(default='BCA Class of 2026 final group photo', max_length=255)),
                ('class_info_title', models.CharField(default='Class Information', max_length=100)),
                ('class_info_text', models.TextField(default='Bachelor of Computer Applications (BCA)\nClass of 2026\nThree years of friendship and memories')),
                ('archive_title', models.CharField(default='The Archive', max_length=100)),
                ('archive_text', models.TextField(default='A photography gallery, video collection, timeline, digital scrapbook and student yearbook.')),
                ('accessibility_title', models.CharField(default='Accessible Anywhere', max_length=100)),
                ('accessibility_text', models.TextField(default='Designed to remain fast, responsive and accessible across mobile phones, tablets, laptops and desktops.')),
                ('creator_name', models.CharField(default='Manoj Kumar S', max_length=100)),
                ('creator_role', models.CharField(default='Lead Developer & Creator', max_length=100)),
                ('creator_description', models.TextField(default='Designed and developed for the BCA Class of 2026 to preserve our college memories in a clean, responsive and lasting digital archive.')),
                ('creator_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('creator_image_alt', models.CharField(default='Manoj Kumar S', max_length=255)),
                ('created_for_text', models.CharField(default='Created for: BCA Class of 2026', max_length=150)),
                ('thanks_badge', models.CharField(default='GRATITUDE & ACKNOWLEDGEMENT', max_length=100)),
                ('thanks_title', models.CharField(default='Special Thanks', max_length=100)),
                ('thanks_text', models.TextField(default='We extend our heartfelt gratitude to our HOD, faculty members, class coordinators, mentors and every classmate who contributed photographs, videos, captions and memories to this archive.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('General', 'General Enquiry'), ('Photo / Memory Submission', 'Photo / Memory Submission'), ('Correction', 'Correction / Update'), ('Technical Issue', 'Technical Issue'), ('Other', 'Other')], default='General', max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_badge', models.CharField(default='GET IN TOUCH', max_length=100)),
                ('intro_title', models.CharField(default='Let’s Keep the Memories Connected.', max_length=200)),
                ('intro_description', models.TextField(default='For feedback, missing memories, corrections, photo submissions, or archive-related queries, get in touch with us.')),
                ('email', models.EmailField(blank=True, default='contact@collegememories26.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='BCA Department, Class of 2026', max_length=200)),
                ('social_label_1', models.CharField(blank=True, default='Instagram', max_length=100)),
                ('social_url_1', models.URLField(blank=True, default='')),
                ('social_label_2', models.CharField(blank=True, default='GitHub', max_length=100)),
                ('social_url_2', models.URLField(blank=True, default='')),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('contact_image_alt', models.CharField(default='College Memories Contact', max_length=255)),
                ('success_message', models.TextField(default='Thank you for reaching out! Your message has been sent successfully.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
    ]
