# Generated by Django 6.0.8 on 2026-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutpage_contactmessage_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_image',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_image_alt',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='background_photos',
            field=models.ManyToManyField(blank=True, help_text='Select existing gallery photos for the About page background drift wall. Fallback will use recent approved photos.', related_name='about_backgrounds', to='core.photo'),
        ),
    ]
