# Generated by Django 6.0.8 on 2026-08-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_contactpage_contact_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='background_photos',
            field=models.ManyToManyField(blank=True, help_text='Select Gallery photos to display in the About page Drift Wall. If no photos are selected, the Drift Wall will remain empty.', related_name='about_backgrounds', to='core.photo'),
        ),
        migrations.CreateModel(
            name='SelectedGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (1 to 10)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this photo in Selected Memories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.OneToOneField(limit_choices_to={'status': 'approved'}, on_delete=django.db.models.deletion.CASCADE, related_name='selected_memory', to='core.photo')),
            ],
            options={
                'verbose_name': 'Selected Memory',
                'verbose_name_plural': 'Selected Memories',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
