# Generated by Django 6.0.8 on 2026-08-16 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_aboutpage_background_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapbookPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('pinned', 'Pinned Moments Desk'), ('film', 'Moving Film Archive'), ('mosaic', 'Torn Memory Mosaic'), ('final', 'The Last Page')], default='pinned', max_length=20)),
                ('custom_title', models.CharField(blank=True, help_text='Optional custom title override for this section.', max_length=200)),
                ('custom_caption', models.TextField(blank=True, help_text='Optional custom caption override for this section.')),
                ('rotation', models.IntegerField(default=0, help_text='Rotation angle in degrees (-3 to 3 recommended for Pinned Moments).')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order within this section.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this photo in the scrapbook section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(limit_choices_to={'status': 'approved'}, on_delete=django.db.models.deletion.CASCADE, related_name='scrapbook_placements', to='core.photo')),
            ],
            options={
                'verbose_name': 'Scrapbook Placement',
                'verbose_name_plural': 'Scrapbook Placements',
                'ordering': ['section', 'display_order', '-created_at'],
            },
        ),
    ]
