# Generated by Django 6.0.8 on 2026-08-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scrapbookplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapbookplacement',
            options={'ordering': ['section', 'display_order', '-created_at'], 'verbose_name': 'Scrapbook Memory', 'verbose_name_plural': 'Scrapbook Memories'},
        ),
        migrations.AlterField(
            model_name='scrapbookplacement',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Rotation angle in degrees (-3 to 3 recommended for Pinned Scratch Memories).'),
        ),
        migrations.AlterField(
            model_name='scrapbookplacement',
            name='section',
            field=models.CharField(choices=[('pinned', 'Pinned / Scratch Memories'), ('film', 'Moving Film Archive'), ('mosaic', 'Memory Mosaic'), ('final', 'Final Memory')], default='pinned', max_length=20),
        ),
    ]
