# Generated by Django 6.0.8 on 2026-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_scrapbookplacement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='show_in_atlas',
            field=models.BooleanField(default=False, help_text='Use this photograph as one of the cover photographs for its Memory Atlas category portal.', verbose_name='Memory Atlas'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this photograph as a featured memory.', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='selectedgalleryphoto',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this photo in Selected Memories.'),
        ),
    ]
