# Generated by Django 6.0.8 on 2026-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_photo_show_in_atlas_alter_photo_is_featured_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scrapbookplacement',
            constraint=models.UniqueConstraint(fields=('photo', 'section'), name='unique_photo_scrapbook_section'),
        ),
    ]
