# Generated by Django 6.0.8 on 2026-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_scrapbookplacement_unique_photo_scrapbook_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='about_order',
            field=models.PositiveIntegerField(default=0, verbose_name='About Order'),
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Gallery Order'),
        ),
        migrations.AddField(
            model_name='photo',
            name='home_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Home Order'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Master active status for this photograph.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='photo',
            name='scrapbook_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Scrapbook Order'),
        ),
        migrations.AddField(
            model_name='photo',
            name='selected_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Selected Order'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_about',
            field=models.BooleanField(default=False, help_text='Display on About Page.', verbose_name='About'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_gallery',
            field=models.BooleanField(default=True, help_text='Display in Main Gallery.', verbose_name='Gallery'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_home',
            field=models.BooleanField(default=False, help_text='Display on Home Page.', verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_scrapbook',
            field=models.BooleanField(default=False, help_text='Display in Scrapbook.', verbose_name='Scrapbook'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_selected_memories',
            field=models.BooleanField(default=False, help_text='Display in Selected Memories.', verbose_name='Selected Memories'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_timeline',
            field=models.BooleanField(default=False, help_text='Display on Timeline.', verbose_name='Timeline'),
        ),
        migrations.AddField(
            model_name='photo',
            name='timeline_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Timeline Order'),
        ),
    ]
