# Generated by Django 6.0.8 on 2026-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_photo_about_order_photo_gallery_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='about_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='About Order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Gallery Order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='home_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Home Order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='scrapbook_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Scrapbook Order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='selected_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Selected Order'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='timeline_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Timeline Order'),
        ),
    ]
