# Generated by Django 6.0.8 on 2026-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_photo_about_order_alter_photo_gallery_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbookplacement',
            name='film_strip',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Film Strip 1'), (2, 'Film Strip 2')], help_text='Film strip selection (1 or 2). Only applicable for Moving Film Archive.', null=True),
        ),
    ]
