# Generated by Django 6.0.8 on 2026-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_scrapbookplacement_film_strip'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scrapbookplacement',
            name='unique_photo_scrapbook_section',
        ),
        migrations.AddConstraint(
            model_name='scrapbookplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('section', 'film')), fields=('photo', 'section', 'film_strip'), name='unique_film_photo_strip'),
        ),
        migrations.AddConstraint(
            model_name='scrapbookplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('section', 'film'), _negated=True), fields=('photo', 'section'), name='unique_nonfilm_photo_section'),
        ),
    ]
