# Generated by Django 6.0.8 on 2026-08-18 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_scrapbookplacement_unique_photo_scrapbook_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'is_active', 'show_gallery'], name='photo_pub_gallery_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'is_active', 'show_in_atlas'], name='photo_pub_atlas_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'is_active', 'is_featured'], name='photo_pub_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapbookplacement',
            index=models.Index(fields=['section', 'film_strip', 'is_active'], name='sp_sec_strip_act_idx'),
        ),
    ]
