# Generated by Django 6.0.8 on 2026-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_photo_photo_pub_gallery_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='story_paragraph_1',
            field=models.TextField(default="Echoes Of SMASC '26 is a digital archive created to preserve the people, journeys, celebrations and everyday moments that defined our three years of college life."),
        ),
    ]
