# Generated by Django 4.2.25 on 2026-08-21 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_aboutpage_story_paragraph_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='yearbook/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='timeline/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'avif', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'm4v'])]),
        ),
        migrations.AddIndex(
            model_name='heroslide',
            index=models.Index(fields=['is_active', 'display_order', 'created_at'], name='hs_act_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'is_active', 'home_order', '-created_at'], name='photo_home_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='selectedgalleryphoto',
            index=models.Index(fields=['is_active', 'order', 'created_at'], name='sgp_act_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_featured', 'display_order', 'name'], name='stu_feat_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['is_featured', 'display_order', 'event_date'], name='tle_feat_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured', 'display_order', '-created_at'], name='vid_feat_ord_idx'),
        ),
    ]
