# Generated by Django 4.2.25 on 2026-08-22 14:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_heroslide_image_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='creator_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='scrapbookitem',
            name='image',
            field=models.ImageField(upload_to='scrapbook/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='yearbook/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='timeline/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[core.validators.validate_video_file]),
        ),
    ]
