"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present (do not override system environment in production)
load_dotenv(BASE_DIR / ".env", override=False)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('true', '1', 't')

# SECURITY WARNING: keep the secret key used in production secret!
raw_secret_key = os.getenv('DJANGO_SECRET_KEY')
if not DEBUG and (not raw_secret_key or raw_secret_key.startswith('django-insecure-')):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY environment variable is required and must not be a default insecure key when DEBUG=False."
    )

SECRET_KEY = raw_secret_key or 'django-insecure-*u@3!ey_3nggvd)ayr97ob)thal_42$jiuo4whct*9!t%e+jk2'


# Production-Safe ALLOWED_HOSTS:
# - In development (DEBUG=True), supports localhost, 127.0.0.1, [::1], and local LAN testing IP (192.168.1.11).
# - In production (DEBUG=False), requires explicit DJANGO_ALLOWED_HOSTS environment variable.
raw_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS')
if raw_allowed_hosts is not None:
    ALLOWED_HOSTS = [host.strip() for host in raw_allowed_hosts.split(',') if host.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '192.168.1.11']
else:
    ALLOWED_HOSTS = []

# Automatically support Render PaaS external hostname if present
render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

raw_csrf_origins = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS')
if raw_csrf_origins is not None:
    CSRF_TRUSTED_ORIGINS = [url.strip() for url in raw_csrf_origins.split(',') if url.strip()]
elif DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://192.168.1.11:8000',
    ]
else:
    CSRF_TRUSTED_ORIGINS = []

if render_hostname:
    render_csrf = f"https://{render_hostname}"
    if render_csrf not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_csrf)

# Security & Browser Hardening
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = os.getenv('DJANGO_X_FRAME_OPTIONS', 'SAMEORIGIN')
SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'False' if DEBUG else 'True').lower() in ('true', '1', 't')
SESSION_COOKIE_SECURE = os.getenv('DJANGO_SESSION_COOKIE_SECURE', 'False' if DEBUG else 'True').lower() in ('true', '1', 't')
CSRF_COOKIE_SECURE = os.getenv('DJANGO_CSRF_COOKIE_SECURE', 'False' if DEBUG else 'True').lower() in ('true', '1', 't')
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False' if DEBUG else 'True').lower() in ('true', '1', 't')
SECURE_HSTS_PRELOAD = os.getenv('DJANGO_SECURE_HSTS_PRELOAD', 'False' if DEBUG else 'True').lower() in ('true', '1', 't')

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.DevCacheControlMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Default: Local SQLite for zero-config development & testing
# Production: Configurable via DATABASE_URL or DB_HOST/DB_NAME/DB_USER/DB_PASSWORD
database_url = os.getenv('DATABASE_URL')
if database_url:
    import urllib.parse
    parsed_db = urllib.parse.urlparse(database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql' if parsed_db.scheme in ('postgres', 'postgresql') else 'django.db.backends.sqlite3',
            'NAME': parsed_db.path.lstrip('/'),
            'USER': parsed_db.username or '',
            'PASSWORD': parsed_db.password or '',
            'HOST': parsed_db.hostname or '',
            'PORT': str(parsed_db.port or 5432) if parsed_db.port else '5432',
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
        }
    }
elif os.getenv('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'pgallery'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Storage backends
USE_S3 = os.getenv('USE_S3', 'False').lower() in ('true', '1', 't') or bool(os.getenv('AWS_STORAGE_BUCKET_NAME'))

if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', '')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', '')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', '')
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'core.storage.DevAutoVersionStaticFilesStorage' if DEBUG else 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

WHITENOISE_MANIFEST_STRICT = False

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Unfold Admin Theme & Navigation Configuration
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_HEADER": "Echoes Of SMASC '26",
    "SITE_TITLE": "Echoes Of SMASC '26",
    "INDEX_TITLE": "Echoes Of SMASC '26 Administration",
    "SITE_ICON": {
        "light": lambda request: "/static/branding/03_RESPONSIVE_ICONS/ES26_256x256.png",
        "dark": lambda request: "/static/branding/03_RESPONSIVE_ICONS/ES26_256x256.png",
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/branding/02_LOGO_VARIANTS/ES26_ROUNDED_512.png",
        "dark": lambda request: "/static/branding/02_LOGO_VARIANTS/ES26_ROUNDED_512.png",
    },
    "SITE_FAVICON": lambda request: "/static/branding/04_FAVICONS_PWA/favicon.ico",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",
    "STYLES": [
        lambda request: "/static/admin/css/image-preview.css",
    ],
    "SCRIPTS": [
        lambda request: "/static/admin/js/image-preview.js",
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 235",
            "100": "245 230 200",
            "200": "235 210 160",
            "300": "225 190 130",
            "400": "215 179 119",
            "500": "200 160 100",
            "600": "180 140 85",
            "700": "150 115 65",
            "800": "120 90 50",
            "900": "90 65 35",
            "950": "60 40 20",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "CONTENT MANAGEMENT",
                "separator": True,
                "items": [
                    {
                        "title": "Hero Slides",
                        "icon": "auto_awesome",
                        "link": reverse_lazy("admin:core_heroslide_changelist"),
                    },
                    {
                        "title": "Photos Gallery",
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:core_photo_changelist"),
                    },
                    {
                        "title": "Timeline Events",
                        "icon": "timeline",
                        "link": reverse_lazy("admin:core_timelineevent_changelist"),
                    },
                    {
                        "title": "Scrapbook Memories",
                        "icon": "auto_stories",
                        "link": reverse_lazy("admin:core_scrapbookplacement_changelist"),
                    },
                    {
                        "title": "Video Memories",
                        "icon": "movie",
                        "link": reverse_lazy("admin:core_video_changelist"),
                    },
                ],
            },
            {
                "title": "PEOPLE & PROFILES",
                "separator": True,
                "items": [
                    {
                        "title": "Classmate Yearbook",
                        "icon": "groups",
                        "link": reverse_lazy("admin:core_student_changelist"),
                    },
                ],
            },
            {
                "title": "SITE PAGES & CONTACT",
                "separator": True,
                "items": [
                    {
                        "title": "About Page",
                        "icon": "info",
                        "link": reverse_lazy("admin:core_aboutpage_changelist"),
                    },
                    {
                        "title": "Contact Page",
                        "icon": "contact_support",
                        "link": reverse_lazy("admin:core_contactpage_changelist"),
                    },
                    {
                        "title": "Contact Messages",
                        "icon": "mail",
                        "link": reverse_lazy("admin:core_contactmessage_changelist"),
                    },
                ],
            },
            {
                "title": "ORGANIZATION",
                "separator": True,
                "items": [
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": reverse_lazy("admin:core_category_changelist"),
                    },
                ],
            },
            {
                "title": "SYSTEM & SECURITY",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# ==============================================================================
# EMAIL NOTIFICATION & SMTP CONFIGURATION
# ==============================================================================
EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "t")
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Echoes Of SMASC <noreply@localhost>")
CONTACT_NOTIFICATION_EMAIL = os.getenv("CONTACT_NOTIFICATION_EMAIL", "admin@localhost")

# ==============================================================================
# UPLOAD LIMITS & SCALABILITY POLICIES
# ==============================================================================
MAX_IMAGE_UPLOAD_SIZE = int(os.getenv("MAX_IMAGE_UPLOAD_SIZE", 25 * 1024 * 1024))  # 25 MB
MAX_VIDEO_UPLOAD_SIZE = int(os.getenv("MAX_VIDEO_UPLOAD_SIZE", 500 * 1024 * 1024))  # 500 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", 50 * 1024 * 1024))  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", 50 * 1024 * 1024))  # 50 MB